### ISSUE TITLE
KA bookmarks

### ISSUE THREAD

**Issue by JettBurns14** [ka-extension/ka-extension-ts#25] opened 2018-04-26 16:36 UTC
**Suggestion:** _"When you click on the extension icon, add a link to the Khan Academy dashboard and another custom KA link the user can pick."_
**Author:** Granttwin

![image](https://user-images.githubusercontent.com/24257648/39319218-0b99ffbe-4946-11e8-9744-29eca5e6d2cb.png)

**Comment by lukekrikorian** [comment] 2018-09-13 14:48
Duplicate of #26.

**Closed by lukekrikorian** 2018-09-13 14:48 UTC
Labels: enhancement
